package com.stonewu.fusion.enums.ai;

public enum AgentRuntimeErrorCode {

    MODEL_AUTH_FAILED,
    MODEL_NOT_FOUND,
    MODEL_PROTOCOL_ERROR,
    MODEL_TIMEOUT,
    TOOL_VALIDATION_FAILED,
    TOOL_TIMEOUT,
    TOOL_CANCELLED,
    STATE_STORE_FAILED,
    EVENT_PERSIST_FAILED,
    AGENT_EVENT_BACKPRESSURE_OVERFLOW,
    HARNESS_CAPACITY_EXHAUSTED,
    RUN_CONFIG_UNAVAILABLE,
    CONFIRMATION_EXPIRED,
    EXTERNAL_EXECUTION_EXPIRED,
    SSE_CURSOR_INVALID,
    OWNER_LOST,
    RUN_CANCELLED,
    AGENTSCOPE_INTERNAL_ERROR;

    public String getCode() {
        return name();
    }
}
