export {
  agentTypeNames,
  assetTypeNames,
  getAgentTypeName,
  getToolDisplayName,
  isSubAgentTool,
  storyboardShotTypeNames,
  subAgentToolNames,
  toolDisplayNames,
} from "../shared/ai-task-display";

const fieldLabels: Record<string, string> = {
  status: "状态",
  message: "信息",
  total: "总数",
  id: "ID",
  name: "名称",
  type: "类型",
  count: "数量",
  title: "标题",
  remark: "备注",
  projectId: "项目ID",
  scriptId: "剧本ID",
  storyboardId: "分镜ID",
  storyboardEpisodeId: "分镜分集ID",
  storyboardSceneId: "分镜场次ID",
  sceneId: "场次ID",
  scriptEpisodeId: "剧本分集ID",
  episodeId: "集ID",
  sceneName: "场次名称",
  sceneNumber: "场次号",
  shotCount: "镜头数",
  sceneCount: "场次数",
  totalItems: "总项数",
  totalEpisodes: "总集数",
  shotNumber: "镜号",
  autoShotNumber: "自动镜号",
  shotType: "景别",
  duration: "时长",
  cameraMovement: "运镜",
  sceneExpectation: "画面预期",
  genre: "类型",
  description: "描述",
  content: "内容",
  url: "链接",
  imageUrl: "图片",
  generatedImageUrl: "生成图片",
  referenceImageUrl: "参考图",
  videoUrl: "视频",
  generatedVideoUrl: "生成视频",
  sceneRef: "场景参考",
  characterRefs: "角色参考",
  propRefs: "道具参考",
  isCurrentTarget: "当前目标",
  createdAt: "创建时间",
  updatedAt: "更新时间",
  storyboards: "分镜列表",
  items: "子项",
  episodes: "集列表",
  assets: "素材列表",
  scripts: "剧本列表",
  projects: "项目列表",
};

export function getFieldLabel(key: string): string {
  return fieldLabels[key] || key;
}